### ISSUE TITLE
malloc.c:22:87: error: use of undeclared identifier 'MAP_ANONYMOUS'

### ISSUE THREAD

**Issue by ryandesign** [ngs-lang/ngs#665]
ngs fails to build on OS X 10.10 and earlier.

```
malloc.c:22:87: error: use of undeclared identifier 'MAP_ANONYMOUS'
```

Here's a recent build log: https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/274533/steps/install-port/logs/stdio

On older macOS and BSD, `MAP_ANONYMOUS` was called `MAP_ANON`. You could use:

```c
#ifndef MAP_ANONYMOUS
#define MAP_ANONYMOUS MAP_ANON
#endif
```

I previously reported this to MacPorts: https://trac.macports.org/ticket/64195

**Comment by ilyash-b** [comment]
Do we have statistics about installations? Is anyone actually using this port on such an old system? The [latest update to that version was in 2017](https://en.wikipedia.org/wiki/MacOS_version_history). I don't know whether it would be a good decision to support that version.

**Comment by ryandesign** [comment]
MacPorts supports Mac OS X 10.4 and later. There are a handful of MacPorts users very passionate about supporting older systems. If you do not wish to include this simple change in your software we can fix it on the MacPorts side by using our [legacy support library](https://github.com/macports/macports-legacy-support) but I like to give upstream developers the chance to fix their software at the source so that it can benefit the largest audience.

**Comment by ryandesign** [comment]
> Do we have statistics about installations?

MacPorts opt-in installation statistics are here: https://ports.macports.org/statistics/

**Comment by ilyash-b** [comment]
I'll need some time to get to this. Need a clean environment to experiment with. Figuring out what would be practical for me.

**Comment by ilyash-b** [comment]
How can I reproduce this? Both AWS AMIs and GitHub actions [images](https://github.com/actions/runner-images/tree/main/images/macos) don't have such old versions. What would be a practical way for me to access an environment in which I can reproduce the issue?
